### ISSUE TITLE
Poor performance on 1000x1000 map

### ISSUE THREAD

**Issue by jiri-kajaba** [jajir/microcol#22]
It takes 5-10 seconds to move mouse cursor.

**Comment by jiri-kajaba** [comment]
Greatly improved performance of path finding. It is OK for 100x100 map but still quite slow for 1000x1000 map.

**Comment by jajir** [comment]
Performance is much more better. Still when I go to longest distance than slow down is still visible. 
<img width="945" alt="screen shot 2017-04-08 at 18 01 57" src="https://cloud.githubusercontent.com/assets/8354612/24830404/c3bd733a-1c85-11e7-8e34-734873bff960.png">

**Comment by abdollheid** [comment]
sorry can u plesse explain the issue and the app  ?

**Comment by jajir** [comment]
After refactoring is performance better. When there will be another problem than A* should be improved.
