### ISSUE TITLE
Endless loop when user try to move to enemy ship

### ISSUE THREAD

**Issue by jajir** [jajir/microcol#23]
When I select top right ship to move in non development map (1000 x 1000) and try to move to opponent ship than game freeze. Most of the time game spend in PathFindingNode.java 30:

`	return parent != null ? parent.getCost() + 1 : 0;`

**Comment by jiri-kajaba** [comment]
There is no endless loop. It just takes very long time to finish, because if there is not any possible path all locations must be checked. I will fix this issue in #22.
