### ISSUE TITLE
Debug menu

### ISSUE THREAD

**Issue by jajir** [jajir/microcol#26]
Add debug menu containing debugging operations. Start/Stop AI. Menu should be available just when some system property is defined.

**Comment by jajir** [comment]
Development menu is available just when following system property is set: 

> -Ddevelopment=true

Start and Stop AI event are not connect to any logic. Please let me know which method on model should be called.

**Comment by jiri-kajaba** [comment]
Engine.suspend/resume

**Comment by jiri-kajaba** [comment]
It is not possible to resume AI. Game freezes (probably problem with threads).
