### ISSUE TITLE
Ships can fight each others.

### ISSUE THREAD

**Issue by jajir** [jajir/microcol#3]
Ships can fight each others. Computer controlled ships should actively attack.

**Comment by jiri-kajaba** [comment]
Basic implementation in model is done. When you finish GUI implementation give this ticket back to me.

**Comment by jajir** [comment]
Game logic should be changed to support attack by moving at attacked map locations.

**Comment by jajir** [comment]
Waiting for #21

**Comment by jiri-kajaba** [comment]
Ship.attack(Location)
