### ISSUE TITLE
GAME IS BROKEN BECAUSE OF ANIMATION SPEED

### ISSUE THREAD

**Issue by jiri-kajaba** [jajir/microcol#31]
It is not working in any situation.

12:16:43.480 [Thread-7] INFO  - Unit moved: UnitMovedEvent{unit=Unit{type=UnitType{name=FRIGATE, speed=4, canAttack=true}, owner=Player{name=Player1, computer=false}, location=Location{x=5, y=4}, availableMoves=2}, start=Location{x=3, y=3}, path=Path{locations=[Location{x=4, y=4}, Location{x=5, y=4}]}}. --> org.microcol.model.ListenerManager.fireUnitMoved(ListenerManager.java:73)
Exception in thread "Thread-7" java.lang.IllegalArgumentException: speed '10' is to high
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:168)
	at org.microcol.gui.PathPlanning.countPositiveStepSize(PathPlanning.java:122)
	at org.microcol.gui.PathPlanning.countStepSize(PathPlanning.java:117)

**Comment by jajir** [comment]
It's about stored preferences, recently allowed speed was from 0 to 10, now it's from 0 to 4. Old value is stored in your local setting and when game starts it's used. Where it is stored should be described at: http://stackoverflow.com/questions/4947555/where-are-the-java-preferences-stored-in-windows-7.

**Comment by jiri-kajaba** [comment]
Does not work.

**Comment by jiri-kajaba** [comment]
It is working. GJ :-)
