### ISSUE TITLE
Missing default localization

### ISSUE THREAD

**Issue by jiri-kajaba** [jajir/microcol#34]
File localization_en_US.xml should be only localization.xml.

1) Error in custom provider, java.util.MissingResourceException: Can't find bundle for base name localization, locale fr_FR
  at org.microcol.gui.MicroColModule.makeText(Unknown Source)
  at org.microcol.gui.MicroColModule.makeText(Unknown Source)

**Comment by jajir** [comment]
Should work now.

**Comment by jiri-kajaba** [comment]
I didn't retest it.
