### ISSUE TITLE
Suspend / Resume AI doesn't work

### ISSUE THREAD

**Issue by jiri-kajaba** [jajir/microcol#37]
Fist selection from menu does nothing.

Seems like second selection works.

**Comment by jiri-kajaba** [comment]
I don't like current check box style solution.

**Comment by jajir** [comment]
Now you can use CTRL.+ left shift + A to stop/start game. You can suggest better solution.

**Comment by jajir** [comment]
Ahoj,

chybu jsem opravil. Jestli to mam nejak upravit, muzem se domluvit na jinem vzhledu. Pripadne tam mas klavesovou zkratku,

zatim ahoj, H.

**Comment by jiri-kajaba** [comment]
Suspend AI - Resume AI
