### ISSUE TITLE
Main menu doesn't work after window resize

### ISSUE THREAD

**Issue by jiri-kajaba** [jajir/microcol#38]

**Comment by jajir** [comment]
Ahoj Jirko,

zkousel jse resizivat okno a klikat na main menu. Normalne mi to funguje. Muzes, prosim, popsat, co presne nefunguje?

dekuju, Honza

**Comment by jiri-kajaba** [comment]
Seems like menu is not shown before movement of current unit is finished.

**Comment by jajir** [comment]
It seams to work.
