### ISSUE TITLE
There will less than 500 checkstyle errors

### ISSUE THREAD

**Issue by jajir** [jajir/microcol#6]
Checkstyle report should contain less than 500 errors.

**Comment by jiri-kajaba** [comment]
Report is not properly set. See for example Location.java. Please remove these:

- File contains tab characters (this is the first instance).
- '(' is followed by whitespace.
- 'x' hides a field.
- javadoc required only for public and protected members (for beginning)

**Comment by jajir** [comment]
There are 489 errors, prority of some checks was changed, some problems was corrected.
