### ISSUE TITLE
There will be two kind of ship

### ISSUE THREAD

**Issue by jajir** [jajir/microcol#8]
Game will support two kind of ships Galeon and Frigade. Ships properties could by copied from following image.

<img width="697" alt="screen shot 2017-03-21 at 22 05 36" src="https://cloud.githubusercontent.com/assets/8354612/24170862/8f99effe-0e82-11e7-8189-21b0508891ea.png">

**Comment by jiri-kajaba** [comment]
Added support of ship types into model.

**Comment by jajir** [comment]
both types of ship are displayed.
