### ISSUE TITLE
Center map

### ISSUE THREAD

**Issue by jajir** [jajir/microcol#9]
When game world area is smaller that visible rectangle than world should be placed in the centre of visible rectangular area.

**Comment by jajir** [comment]
When AI fight with AI ot map test-map-2islands-15x10.txt and window size is bigger than map than map is placed to top left corner. See following picture:

![centrovani](https://cloud.githubusercontent.com/assets/8354612/26801409/1a3df452-4a3d-11e7-8464-f43f021c1b4c.png)

**Comment by jiri-kajaba** [comment]
Seems fixed.
